### PR TITLE
Simplify without-logging-status

### PR DESCRIPTION
**Pull request by malchmih**

### CODE REVIEW

**Comment by tolitius** [comment]
thanks! are you using this as a stand alone file in your apps?

(the reason I did not want to include it with mount was due to a need to bring tools.logging and robert.hook deps)

**Comment by malchmih** [comment]
Yeah, I've copied it from here, it was a nice addition :blush: You are right to keep it out of the mount itself. 
By the way, I'm using: [cljfmt](https://github.com/weavejester/cljfmt), [kibit](https://github.com/jonase/kibit), [eastwood](https://github.com/jonase/eastwood) and [bikeshed](https://github.com/dakrone/lein-bikeshed) for all my projects, one of them caught this one (not cljfmt, included for the whole picture).

**Comment by tolitius** [comment]
makes sense. just had a thought.. why not to incorporate kibit, eastwood, bikeshed and others under [boot-check](https://github.com/tolitius/boot-check) :) starting with kibit..

**Comment by malchmih** [comment]
You are the best! To tell you the truth, I was waiting for someone to implement that functionality :wink: It is (was) the only missing piece of `lein` functionality in `boot`, in my opinion.

**Comment by tolitius** [comment]
yea, I agree, these tools should be really useful in boot land. I added kibit, yagni, eastwood and bikeshed for now: https://github.com/tolitius/boot-check/blob/master/README.md#boot-check

**Pull request merged**
