### PR TITLE
Add docstring for defstate

### PR DESCRIPTION
**Pull request by kenrestivo**
I keep forgetting the syntax for this. Rather than having to go diving for the README all the time, would be good to have this vital information. in the docstring.

### CODE REVIEW

**Comment by arichiardi** [comment]
Very good addition :+1:

**Comment by tolitius** [comment]
agree, thanks!

**Comment by NOBLES5E** [comment]
@tolitius Can an example usage of docstring be shown in the project README? Otherwise people won't know they can add docstring. 

====
Oh sorry I thought this PR means I can add docstring for a state until I read the code.. Is there anyway to add docstring?...

**Comment by tolitius** [comment]
```clojure
dev=> (doc mount/defstate)
-------------------------
mount.core/defstate
([state & body])
Macro
  Defines a state. Restarts on recompilation.
   Pass ^{:on-reload :noop} to prevent auto-restart
   on ns recompilation, or :stop to stop on recompilation.
```

```clojure
dev=> (defstate answer
        "answer to the ultimate question of life universe and everything"
        :start (+ 1 41))
#'dev/answer
dev=> (mount/start #'dev/answer)
{:started ["#'dev/answer"]}
dev=> answer
42
```
```clojure
dev=> (doc answer)
-------------------------
dev/answer
  answer to the ultimate question of life universe and everything
```

you mean something like this?

**Comment by NOBLES5E** [comment]
Exactly. Thanks!!

**Pull request merged**
