### PR TITLE
Do not start a DerefableState as a side-effect of printing

### PR DESCRIPTION
**Pull request by grammati**
See: https://github.com/clojure/clojure/blob/b80e1fe4b14654d943e2f8b060b0bc56e18b4757/src/clj/clojure/core_print.clj#L422-L446

### CODE REVIEW

**Comment by grammati** [comment]
Fixes #75

**Comment by tolitius** [comment]
thanks for the pull request!

I'll let you pick, but what about instead of:

```clojure
  (#?(:clj isRealized
      :cljs -realized?)
    [_]
    (boolean (:started (:status (@meta-state name)))))
```

do

```clojure
  (#?(:clj isRealized
      :cljs -realized?)
    [_]
    (boolean ((running-states) name)))
```

`running-states` returns a set of states that are currently running. I feel it'd be a bit cleaner than to use `@meta-state` directly.

**Comment by grammati** [comment]
Thanks, that looks nicer. I pushed an update to use running-states.

**Comment by tolitius** [comment]
looks good, thank you!

**Pull request merged**
