### PR TITLE
Fix clj-kondo config, part 2

### LINKED ISSUE #135: Clj-kondo incorrect warning when using docstring for defstate
Having defstate like that (which is also mentioned as valid in README):
```code
(defstate "my doc" :start (try ...) :stop (when ...))
```

Will raise clj-kondo warning saying:
lifecycle functions can only contain `:start` and `:stop`. illegal function found:

Removing docstring
```code
(defstate  :start (try ...) :stop (when ...))
```
removes the warning.

### LINKED ISSUE #136: Clj-kondo warning on defstate deref.
When doing deref on defstate variable clj-kondo throws warning that the deref is done on the return value. Not understanding it is an atom.

```code
(defstate routes
          :start
          (do ["a" "b"]) )
          
  @routes 
 
```
Message: "Expected: deref, received vector. [type-mismatch]

or 
```code
(defstate routes
          :start
          (prn "hello"))
          
  @routes 
 
```
Message: "Expected: deref, received nil. [type-mismatch]

### PR DESCRIPTION
**Pull request by NoahTheDuke**
My apologies for the delay, life gets in the way.

```clojure
(defstate routes
  "Hello world"
  :start (prn "hello"))
```
is now treated in clj-kondo as:
```clojure
(def routes
  "Hello world"
  (atom (do :start (prn "hello"))))
```

Closes #135
Closes #136

### CODE REVIEW

**Comment by tolitius** [comment]
all good, thanks for the fix

**Comment by tolitius** [comment]
the fix is in [[mount "0.1.20"]](https://clojars.org/mount/versions/0.1.20) 

@Kaspazza, just to make sure: does the updated config work as expected for you now?

**Comment by Kaspazza** [comment]
@tolitius @NoahTheDuke Thanks for fixing that! I've tested and now there is no warning.

**Comment by imrekoszo** [comment]
This change appears to have broken linting for one of our projects. Pure clj project, using mount states _without_ dereferencing, linter gives tons of `error: Expected: seqable collection, received: atom. [:type-mismatch]`

**Comment by NoahTheDuke** [comment]
Looking at mount's code, `defstate` produces a `DerefableState` which is a `deftype` that implements IDeref. ([source](https://github.com/tolitius/mount/blob/08173bc6a1f60e5a2f362d5f9f86231529c2aaf5/src/mount/core.cljc#L109-L127)) I don't see where it implements ISeq or similar.

Do you have example code of the errors?

**Comment by imrekoszo** [comment]
Once the state is started it will be replaced by its value however (from the readme):
image

Here's a quick repro (based on the readme, showing how some of our code uses states):
image

Another example from the readme showing that you should be able to use states without explicitly dereferencing them:
image

**Comment by NoahTheDuke** [comment]
i understand my mistake. i'll put up a pr tonight.

**Comment by imrekoszo** [comment]
Thanks @NoahTheDuke. This isn't a trivial one due to the type change over time and I can see why it makes sense to treat it like an atom at times.

**Pull request merged**
