### PR TITLE
Add back possibility to have a function as a state value

### PR DESCRIPTION
**Pull request by aroemers**
Issue #20 adds a lot of flexibility, but removed the possibility to have a function as a state value. This patch brings that back.

### CODE REVIEW

**Comment by tolitius** [comment]
I believe you already added a "possibility to have a function as a state value" with the [power of thought](https://github.com/tolitius/mount/issues/20#issuecomment-160675129) rather than a pull request :) Do you still see a need for this?

**Comment by tolitius** [comment]
ah.. I see what you mean, good catch! I did not want to push it myself since it is your idea, but I'd like to [rename things a bit](https://github.com/tolitius/mount/commit/5619fb0a27d2fbd98f78a18e67388c91819c56ab) and I'll merge it.

**Comment by tolitius** [comment]
@aroemers: gave it a bit more thought. why do we need `trampoline` at all? since it is always ``(fn [] ~value)`, we can always just call that fn.

[here](https://github.com/tolitius/mount/blob/0.1.5/test/check/fun_with_values_test.clj) is where I am coming from.

It will be consistent with the current API: no additional syntax need for an fn-state corner case, and will actually simplify #18 by a lot.

**Comment by aroemers** [comment]
Got to sleep now, but quick response, consider this case:

```
(defn- start-fn [] ...)

(defstate foo :start start-fn)
```

**Comment by tolitius** [comment]
@aroemers: you mean something like [this](https://github.com/tolitius/mount/blob/0.1.5/test/check/fun_with_values_test.clj#L22) being [used](https://github.com/tolitius/mount/blob/0.1.5/test/check/private_fun_test.clj#L14) in another namespace?

**Comment by aroemers** [comment]
@tolitius Not really, what I meant is that `start-fn` above is called when starting the state. So, to complete my example:

``` clj
(defn- start-fn [] "bar")

(defstate foo :start start-fn)

(mount/start)

foo
;=> "bar"
```

Of course, maybe it is just a trade-off, and functions should not be supported in this way, only forms. Above example would only need this change to work without a trampoline:

``` clj
(defstate foo :start (start-fn))
```

**Comment by tolitius** [comment]
@aroemers I'd prefer a simple syntax with the understanding of `(f)` vs. `f`

the idea was that state's `:start` will be "invoked" on (mount/start). values came later from @xhh and your contributions :)

**Comment by aroemers** [comment]
@tolitius Alright, I respect that choice. Closing this one then.

**Pull request closed without merging**
